name: flashcards_angular
version: 0.0.1
description: AngularDart view of flashcards.

environment:
  sdk: ">=2.0.0-dev.46.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha
#  angular_components: ^0.9.0-alpha+8
#  angular_forms: ^1.0.1-alpha+7
  markdown: ^1.1.1
  meta: '^1.1.2'
  firebase: '^4.3.0'
  flashcards_common:
    path: ../common

dev_dependencies:
  sass_builder: ^1.1.5
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.2
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.6
  mockito: ^2.2.3
  test: ^0.12.32+1
