name: flashcards_common
version: 0.0.1
description: Common things of flashcards.

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  meta: '^1.1.2'
  intl: '^0.15.2'
  tuple: '^1.0.1'

dev_dependencies:
  test: '^0.12.0'
  intl_translation: '0.16.3'
